server:
  port: 8888
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
  datasource:
    url: jdbc:mysql://localhost:3306/fast-crud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl